default:
    tags:
        - shared-runner:nfs

variables:
    CMAKE_PAK: $CI_COMMIT_REF_SLUG
    KUBERNETES_CPU_LIMIT: "16"
    KUBERNETES_MEMORY_REQUEST: "8Gi"


# Components to include
include:
    - component: $CI_SERVER_HOST/habitat/ci-components/wak-components/deploy@1
      inputs:
          job-name: full_build_test
          waf-app-version-name: $CMAKE_PAK
    - component: $CI_SERVER_HOST/habitat/ci-components/wak-components/release_from_tag@1
      inputs:
          wak-tag-prefix: weta/
    - component: $CI_SERVER_HOST/habitat/ci-components/wak-components/deploy_custom_version@1
      inputs:
          wak-tag-prefix: weta/
          waf-app-version-name: $CMAKE_PAK


stages:
    # Component specific stages
    - build
    - test
    - release
    - validate


# Update the rules for the build to trigger on MR instead of branch
full_build_test:
    only:
        - merge_requests


# Trigger a full build of the cmake-wak template project using
# our just-built cmake pak.
#
# NOTE: The CMAKE_PAK variable is forwarded to all children
test_cmake_template:
    stage: test
    only:
        - merge_requests
    trigger:
        project: habitat/templates/cmake-wak
        branch: main
        strategy: depend

test_cmake_provider:
    stage: test
    only:
        - merge_requests
    trigger:
        project: buildenv/weta-cmake-provider
        branch: main
        strategy: depend